---
- hosts: localhost
  become: no

  tasks:

    - set_fact:
        target_user_name: '{{ ansible_user_id }}'
        target_home_dir: '{{ ansible_user_dir }}'

- hosts: localhost
  become: yes

  tasks:

    - name: Copy packages file
      copy:
        src: arch-packages.txt
        dest: /tmp/arch-packages.txt

    - name: Install pacaur
      shell: pacman -Syu --noconfirm pacaur

    - name: Install pacakges
      shell: pacaur -Syu --noedit --noconfirm - < /tmp/arch-packages.txt
      become: no

    - name: Disable system beep
      copy:
        dest: /etc/modprobe.d/nobeep.conf
        content: blacklist pcspkr

    - name: Set X keyboard repeat rate in LightDM
      lineinfile:
        dest: /etc/lightdm/lightdm.conf
        regexp: '(# )?xserver-command=X.*'
        line: 'xserver-command=X -ardelay 200 -arinterval 25'

    - name: Add user to docker group
      user:
        name: '{{ target_user_name }}'
        groups: docker
        append: yes

    - name: Restart Docker service
      service:
        name: docker
        state: started

    - name: Enable Redshift
      shell: systemctl --user enable redshift
      become: no

    - name: Download ZeroTier-One
      git:
        repo: https://github.com/zerotier/ZeroTierOne.git
        dest: /opt/ZeroTierOne
        accept_hostkey: yes

    - name: Install ZeroTier-One
      shell: 'make && make install'
      args:
        chdir: /opt/ZeroTierOne
