---
- hosts: localhost
  become: no

  tasks:

    - name: Create ~/.docker
      file:
        state: directory
        path: "{{ ansible_user_dir }}/.docker"

- hosts: localhost
  become: yes
  gather_facts: no

  tasks:

    - name: Download ZeroTier-One
      git:
        repo: https://github.com/zerotier/ZeroTierOne.git
        dest: /opt/ZeroTierOne
        accept_hostkey: yes

    - name: Install ZeroTier-One
      shell: 'make && make install'
      args:
        chdir: /opt/ZeroTierOne

    - name: Stop Docker service
      service:
        name: docker
        state: stopped

    - name: Link /var/lib/docker to ~/.docker
      file:
        state: link
        force: yes
        src: "{{ ansible_user_dir }}/.docker"
        dest: /var/lib/docker

    - name: Add user to docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Restart Docker service
      service:
        name: docker
        state: started
