---
- hosts: localhost

  tasks:

    - name: Create ~/.docker
      file:
        state: directory
        path: "{{ ansible_user_dir }}/.docker"

- hosts: localhost
  become: yes
  gather_facts: no

  tasks:

    - name: Download Gcloud SDK
      unarchive:
        copy: no
        src: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-135.0.0-linux-x86_64.tar.gz
        dest: /opt/

    - fail:

    - name: Install ZeroTier One
      shell: curl -s https://install.zerotier.com/ | bash

    - name: Link /var/lib/docker to ~/.docker
      file:
        state: link
        force: yes
        src: "{{ ansible_user_dir }}/.docker"
        dest: /var/lib/docker

    - name: Install Docker
      shell: curl -sSL https://get.docker.com/ | sed 's/sleep /sleep ./g' | sh
      args:
        creates: /usr/bin/docker

    - name: Add user to docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes
